### ISSUE TITLE
Unreal Engine updates when?

### ISSUE THREAD

**Issue by BlueprintBailey** [caiofelipempe/UnrealEnginePluginDevelopment-4.27#1]
Dear Caio,

Everyone has been enjoying using your plugin, even going beyond 4.27. However, we would like you to FINALLY give us all updates for the plugin so we won't have a hassle in using it on newer versions of Unreal Engine. The sooner you can answer us if you can even hear us, the better.

Thank you for your time.

Yours Truly,

Herogon

**Comment by caiofelipempe** [comment]
Hi,

I am not working on the plug-in for a lot of time, I actually work on that
just as hobby, but if you want the source code, I think the repository link
is on the description of the plug-in in the store, the repository is
public. If you don't find the link you can tell me and send to you.

**Comment by caiofelipempe** [comment]
The link:
https://github.com/caiofelipempe/UnrealEnginePluginDevelopment-4.27
